---
- name: condition test
  hosts: private
  gather_facts: False

  tasks:
    - name: shell command - /usr/bin/foo
#      shell: python3 --version
      shell: py3 --version
      register: result
      ignore_errors: True

    - debug:
        var: ansible_facts

    - debug:
        msg: "{{ result.stederr }}" 
      when: result is failed

    - debug:
        msg: "{{ result.stdout }}"
      when: result is changed
