---
- name: install and running web server
  hosts: public
  gather_facts: False
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
        
    - name: start httpd
      systemd:
        name: httpd
        state: started
      register: result
      ignore_errors: true

    - name: state httpd
      debug:        
        var: result
