---
- name: remove webserver
  hosts: public
  gather_facts: False
  become: yes

  tasks:
    - name: stop httpd
      service:
        name: httpd
        state: stopped

    - name: remove httpd
      yum:
        name: httpd
        state: absent

    - name: remove home directory
      file:
        path: /var/www
        state: absent
